create table if not exists public.users
(
    id     integer generated by default as identity
        constraint pk_table_id
            primary key,
    name   varchar(255) not null
        constraint unq_name
            unique,
    password text         not null,
    email   varchar(255) not null
);

alter table public.users
    owner to postgres;

create table if not exists public.sessions
(
    id           integer generated by default as identity
        constraint pk_session_id
            primary key,
    token        text    not null,
    user_id      integer not null
        constraint fk_sessions_users
            references public.users
            on update cascade on delete cascade,
    session_time timestamp with time zone
);

alter table public.sessions
    owner to postgres;

create unique index if not exists sessions_token_uindex
    on public.sessions (token);

create unique index if not exists sessions_id_uindex
    on public.sessions (id);

